# Generated by Django 4.1.7 on 2023-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_saleinvoiceitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='voided',
            field=models.BooleanField(default=False),
        ),
    ]
