# Generated by Django 4.1.7 on 2025-09-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorytype_product_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('SB', 'Para venta'), ('EV', 'Para eventos'), ('SP', 'Supplies')], default='SB', max_length=2),
        ),
        migrations.DeleteModel(
            name='InventoryType',
        ),
    ]
