# Generated by Django 4.1.7 on 2025-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_inventory_type_delete_inventorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('SB', 'Para venta'), ('EV', 'Para eventos'), ('SP', 'Suministros')], default='SB', max_length=2),
        ),
    ]
