# Generated by Django 4.1.7 on 2025-09-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_type',
            field=models.CharField(choices=[('RS', 'Venta normal'), ('EV', 'Evento')], default='RS', max_length=2),
        ),
    ]
