# Generated by Django 4.1.7 on 2025-09-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_saleinvoice_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
