# Generated by Django 4.1.7 on 2025-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_min_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_type', models.CharField(choices=[('IN', 'Ingreso de efectivo'), ('OUT', 'Retiro de efectivo')], max_length=3)),
            ],
            options={
                'verbose_name': 'Flujo de efectivo',
                'verbose_name_plural': 'Flujos de efectivo',
            },
        ),
    ]
