# Generated by Django 4.1.7 on 2025-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseitem_purchase_date_saleinvoiceitem_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('SB', 'Para venta'), ('EV', 'Para eventos'), ('SP', 'Suministros'), ('ME', 'Menu')], default='SB', max_length=2),
        ),
    ]
