# Generated by Django 4.1.7 on 2025-09-06 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0017_alter_product_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('SB', 'Para venta'), ('EV', 'Para eventos'), ('SP', 'Suministros'), ('ME', 'Menu'), ('CE', 'Para consumo de empleado')], default='SB', max_length=2),
        ),
        migrations.CreateModel(
            name='ComidaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comida de empleado',
                'verbose_name_plural': 'Comidas de empleados',
            },
        ),
    ]
