# Generated by Django 4.1.7 on 2025-10-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_product_inventory_type_comidaempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('SB', 'Para venta'), ('EV', 'Para eventos')], default='SB', max_length=2),
        ),
        migrations.DeleteModel(
            name='ComidaEmpleado',
        ),
    ]
