# Generated by Django 4.1.7 on 2025-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_product_inventory_type_delete_comidaempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
