# Generated by Django 4.1.7 on 2025-10-05 07:54

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_saleinvoiceitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=computed_property.fields.ComputedIntegerField(compute_from='low_stock', editable=False),
        ),
    ]
