# Generated by Django 4.1.7 on 2025-10-05 07:56

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_low_stock',
            field=computed_property.fields.ComputedIntegerField(compute_from='low_stock', default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
