# Generated by Django 4.1.7 on 2025-10-05 07:56

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_product_is_low_stock_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_low_stock',
            field=computed_property.fields.ComputedBooleanField(compute_from='low_stock', editable=False),
        ),
    ]
