# Generated by Django 4.1.7 on 2025-10-05 08:03

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_product_is_low_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_low_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='supplied',
            field=computed_property.fields.ComputedBooleanField(compute_from='is_supplied', default=True, editable=False),
            preserve_default=False,
        ),
    ]
