# Generated by Django 4.1.7 on 2025-10-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_product_is_low_stock_product_supplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoiceitem',
            old_name='total',
            new_name='subtotal',
        ),
    ]
