# Generated by Django 4.1.7 on 2025-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rename_total_saleinvoiceitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
