# Generated by Django 4.1.7 on 2025-10-05 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_cashflow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
