# Generated by Django 4.1.7 on 2025-10-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_cashflow_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
