# Generated by Django 4.1.7 on 2025-10-07 06:13

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplied',
            field=computed_property.fields.ComputedBooleanField(compute_from='is_supplied', default=False, editable=False),
        ),
    ]
