# Generated by Django 4.1.7 on 2025-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_product_supplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplied',
            field=models.BooleanField(default=False),
        ),
    ]
